language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
sudo: required
dist: xenial
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql --version
  - psql -c 'create user pguser;' -U postgres
  - psql -c 'alter user pguser createdb; ' -U postgres
install:
  - cp env.ini.tests env.ini
  - pip install --upgrade -r requirements.txt
  - pip freeze
  - pwd
  - lsb_release -a
script:
  - cd speedy/net
  - python tests_manage.py test speedy.core # python -W error::DeprecationWarning tests_manage.py test speedy.core
  - python tests_manage.py test speedy.net # python -W error::DeprecationWarning tests_manage.py test speedy.net
  - python tests_manage.py test speedy.match # python -W error::DeprecationWarning tests_manage.py test speedy.match
  - python tests_manage.py test speedy.composer # python -W error::DeprecationWarning tests_manage.py test speedy.composer
  - python tests_manage.py test speedy.mail # python -W error::DeprecationWarning tests_manage.py test speedy.mail
  - cd ../match
  - python tests_manage.py test speedy.core # python -W error::DeprecationWarning tests_manage.py test speedy.core
  - python tests_manage.py test speedy.net # python -W error::DeprecationWarning tests_manage.py test speedy.net
  - python tests_manage.py test speedy.match # python -W error::DeprecationWarning tests_manage.py test speedy.match
  - python tests_manage.py test speedy.composer # python -W error::DeprecationWarning tests_manage.py test speedy.composer
  - python tests_manage.py test speedy.mail # python -W error::DeprecationWarning tests_manage.py test speedy.mail
  - cd ../composer
  - python tests_manage.py test speedy.core # python -W error::DeprecationWarning tests_manage.py test speedy.core
  - python tests_manage.py test speedy.net # python -W error::DeprecationWarning tests_manage.py test speedy.net
  - python tests_manage.py test speedy.match # python -W error::DeprecationWarning tests_manage.py test speedy.match
  - python tests_manage.py test speedy.composer # python -W error::DeprecationWarning tests_manage.py test speedy.composer
  - python tests_manage.py test speedy.mail # python -W error::DeprecationWarning tests_manage.py test speedy.mail
  - cd ../mail
  - python tests_manage.py test speedy.core # python -W error::DeprecationWarning tests_manage.py test speedy.core
  - python tests_manage.py test speedy.net # python -W error::DeprecationWarning tests_manage.py test speedy.net
  - python tests_manage.py test speedy.match # python -W error::DeprecationWarning tests_manage.py test speedy.match
  - python tests_manage.py test speedy.composer # python -W error::DeprecationWarning tests_manage.py test speedy.composer
  - python tests_manage.py test speedy.mail # python -W error::DeprecationWarning tests_manage.py test speedy.mail
