language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7" # Raises a DeprecationWarning with Django 1.11.* - see https://code.djangoproject.com/ticket/30078
sudo: required
dist: xenial
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql --version
  - psql -c 'create user pguser;' -U postgres
  - psql -c 'alter user pguser createdb; ' -U postgres
install:
  - cp env.ini.example env.ini
  - pip install -r requirements.txt
  - pip freeze
  - pwd
  - lsb_release -a
script:
  - cd speedy/net
  - python -W error::DeprecationWarning manage.py test
  - cd ../match
  - python -W error::DeprecationWarning manage.py test
  - cd ../composer
  - python -W error::DeprecationWarning manage.py test
  - cd ../mail
  - python -W error::DeprecationWarning manage.py test
