version: '3'

services:

  net:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    env_file:
      - env.docker.ini
    environment:
      - CURRENT_SITE=net
    depends_on:
      - db
      - memcached
    volumes:
      - .:/app
    ports:
      - 8010:8010
    command: runserver 0.0.0.0:8010

  match:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    env_file:
      - env.docker.ini
    environment:
      - CURRENT_SITE=match
    depends_on:
      - db
      - memcached
    volumes:
      - .:/app
    ports:
      - 8020:8020
    command: runserver 0.0.0.0:8020

  composer:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    env_file:
      - env.docker.ini
    environment:
      - CURRENT_SITE=composer
    depends_on:
      - db
      - memcached
    volumes:
      - .:/app
    ports:
      - 8030:8030
    command: runserver 0.0.0.0:8030

  mail:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    env_file:
      - env.docker.ini
    environment:
      - CURRENT_SITE=mail
    depends_on:
      - db
      - memcached
    volumes:
      - .:/app
    ports:
      - 8040:8040
    command: runserver 0.0.0.0:8040

  static:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    volumes:
      - ./themes:/app/themes
      - ./speedy/core/static/themes:/app/speedy/core/static/themes
    command: npm run watch

  db:
    image: postgres:10.3-alpine
    ports:
      - 39887:5432
    environment:
      - POSTGRES_USER=speedy
      - POSTGRES_DB=speedy
    volumes:
      - postgres:/var/lib/postgresql/data

  memcached:
    image: memcached:1.4-alpine

volumes:
  postgres: {}
